# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import conn_pb2 as conn__pb2


class Txt2ImgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Txt2Img = channel.unary_unary(
                '/conn.Txt2ImgService/Txt2Img',
                request_serializer=conn__pb2.ImageRequest.SerializeToString,
                response_deserializer=conn__pb2.ImageResponse.FromString,
                )


class Txt2ImgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Txt2Img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Txt2ImgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Txt2Img': grpc.unary_unary_rpc_method_handler(
                    servicer.Txt2Img,
                    request_deserializer=conn__pb2.ImageRequest.FromString,
                    response_serializer=conn__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conn.Txt2ImgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Txt2ImgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Txt2Img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/conn.Txt2ImgService/Txt2Img',
            conn__pb2.ImageRequest.SerializeToString,
            conn__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
