# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conn.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nconn.proto\x12\x04\x63onn\"\x1e\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"#\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"3\n\x0cVideoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"#\n\rVideoResponse\x12\x12\n\nvideo_data\x18\x01 \x01(\x0c\x32\x46\n\x0eTxt2ImgService\x12\x34\n\x07Txt2Img\x12\x12.conn.ImageRequest\x1a\x13.conn.ImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=20
  _globals['_IMAGEREQUEST']._serialized_end=50
  _globals['_IMAGERESPONSE']._serialized_start=52
  _globals['_IMAGERESPONSE']._serialized_end=87
  _globals['_VIDEOREQUEST']._serialized_start=89
  _globals['_VIDEOREQUEST']._serialized_end=140
  _globals['_VIDEORESPONSE']._serialized_start=142
  _globals['_VIDEORESPONSE']._serialized_end=177
  _globals['_TXT2IMGSERVICE']._serialized_start=179
  _globals['_TXT2IMGSERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
