model_name: 'sd_turbo'
batch_configs: [32,32,32]
locations: ['cuda:3','cuda:3','cuda:4']
lowvram_mode: False
dtype: 'half'
default_steps: 1
model: {
        "H": 512,
        "W": 512,
        "C": 4,
        "f": 8,
        "is_legacy": False,
        "config": "configs/inference/sd_2_1.yaml",
        "ckpt": "checkpoints/sd_turbo.safetensors",
    }